---
title: Defender Andalucía
author: Defender Andalucía
email: defenderandalucia@gmail.com
description: Organización política andaluza que defiende una Andalucía soberanista,
  feminista y socialista
baseurl: "/defenderandalucia"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
